stages:
  prepare_data:
    cmd: python src/data/make_dataset.py
    deps:
      - src/data/make_dataset.py
      - data/raw
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  train_model:
    cmd: python src/models/train.py
    deps:
      - src/models/train.py
      - data/processed/train.csv
    outs:
      - models/model.pkl
    metrics:
      - metrics.json:
          cache: false

  evaluate_model:
    cmd: python src/models/evaluate.py
    deps:
      - src/models/evaluate.py
      - models/model.pkl
      - data/processed/test.csv
    metrics:
      - metrics.json:
          cache: false